# Generated by Django 5.1.6 on 2025-02-18 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
        ('users', '0003_remove_user_created_user_remove_user_updated_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='caseimage',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='case_images', to='users.user'),
        ),
        migrations.AlterField(
            model_name='case',
            name='case_number',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='caseimage',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='cases.case'),
        ),
        migrations.AlterField(
            model_name='caseimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='cases/images/'),
        ),
        migrations.AlterField(
            model_name='caseimage',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='cases/videos/'),
        ),
    ]
