# Generated by Django 5.1.6 on 2025-02-11 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_remove_case_created_user_remove_case_updated_user_and_more'),
        ('users', '0002_alter_user_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='users.user'),
        ),
    ]
